
import os
import yt_dlp

DOWNLOAD_DIR = "downloads"
os.makedirs(DOWNLOAD_DIR, exist_ok=True)


def download_youtube_audio(url: str, audio_format: str) -> str:
    """
    Download the highest-quality audio from a YouTube video
    and convert it to WAV or MP3.
    """

    output_path = os.path.join(
        DOWNLOAD_DIR,
        "%(title)s.%(ext)s"
    )

    ydl_opts = {
        # Download the best available audio
        "format": "bestaudio/best",

        # Output filename
        "outtmpl": output_path,

        # Convert audio to selected format
        "postprocessors": [
            {
                "key": "FFmpegExtractAudio",
                "preferredcodec": audio_format,
                "preferredquality": "0" if audio_format == "mp3" else None,
            }
        ],

        "quiet": False,
        "noplaylist": True,
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)

        # Get the filename generated by yt-dlp
        original_filename = ydl.prepare_filename(info)

        # Replace the original extension with selected format
        output_filename = os.path.splitext(original_filename)[0] + f".{audio_format}"

    return output_filename


def main():
    print("===== YouTube Audio Downloader =====")

    url = input("Enter YouTube URL: ").strip()

    print("\nChoose audio format:")
    print("1. WAV")
    print("2. MP3")

    choice = input("Enter your choice (1/2): ").strip()

    if choice == "1":
        audio_format = "wav"
    elif choice == "2":
        audio_format = "mp3"
    else:
        print("Invalid choice.")
        return

    print("\nDownloading highest-quality audio...")

    try:
        file_path = download_youtube_audio(url, audio_format)

        print("\nDownload completed successfully!")
        print(f"File saved at: {file_path}")

    except Exception as e:
        print(f"\nDownload failed: {e}")


if __name__ == "__main__":
    main()
